export const navigateUrl = {
  main: '/',
  login: '/login',
  search: '/search/:string',
  bookList: '/booklist',
  bookDetail: '/bookdetail/:bookId',
  borrowBook: '/borrowbook/qr/:bookNumber',
  borrowedList: '/borrowedlist',
  returnPage: '/returnpage/qr/:state',
  createQR: '/qr/create',
  adminBookList: '/admin/booklist',
  adminAddBookNew: '/admin/addbook/new',
  adminAddBookUpdate: '/admin/addbook/:id',
  adminBorrowedList: '/admin/borrowedlist',
  adminReturnList: '/admin/returnlist',
  adminUserList: {
    base: '/admin/userlist',
    search: '/admin/:userlist',
  },
};
